# -*- coding: utf-8 -*-
"""DataWarehouse_Retaillogs_67160233.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k8-gL1ZRKtxPgbHxNDsvolxTDfGVYqC3
"""

from __future__ import annotations

from pathlib import Path
import re
import sqlite3
import pandas as pd

PROJECT_DIR = Path.cwd()
DATA_PATH = PROJECT_DIR / "retail_logs.csv"
OUTPUT_DIR = PROJECT_DIR / "output"
OUTPUT_DIR.mkdir(exist_ok=True)
DB_PATH = OUTPUT_DIR / "retail_warehouse.db"

"""ETL Pipeline สำหรับ retail_logs.csv

ลำดับ:
Phase 1        Extract
Phase 2A       Transform (Dimension Tables)
Phase 2B       Transform (Fact Table)
Phase 3A       Load (ตั้งค่า SQLite Warehouse)
Phase 3B       Load (บังคับใช้ Star Schema Relationship)
Phase 3C       Load (ผลักข้อมูลลง Warehouse)
Verification   ทดสอบคิวรีจาก Warehouse
"""

# Helpers

def clean_text(value: object, default: str = "Unknown") -> str:
    if pd.isna(value) or str(value).strip() == "":
        return default
    return " ".join(str(value).strip().split()).title()


def clean_number(value: object) -> float | None:
    if pd.isna(value) or str(value).strip() == "":
        return None
    cleaned = re.sub(r"[^0-9.\-]", "", str(value))
    return float(cleaned) if cleaned else None


def parse_mixed_date(value: object) -> pd.Timestamp:
    text = "" if pd.isna(value) else str(value).strip()
    # ข้อมูลจริงพบ 3 รูปแบบ: 2026-03-15 / 14-May-2026 / 17/05/2026
    for fmt in ["%Y-%m-%d", "%d-%b-%Y", "%d/%m/%Y"]:
        parsed = pd.to_datetime(text, format=fmt, errors="coerce")
        if not pd.isna(parsed):
            return parsed
    return pd.NaT


# Phase 1: Extract

def extract() -> pd.DataFrame:
    df = pd.read_csv(DATA_PATH, dtype=str, encoding="utf-8-sig")
    df.columns = [c.strip().lower() for c in df.columns]
    print(f"[Phase 1 - Extract] raw rows={len(df):,}, duplicate sale_id={df.duplicated('sale_id').sum():,}")
    return df


# Phase 2A: Transform - Dimension Tables

def transform_dimensions(df: pd.DataFrame):
    df = df.drop_duplicates(subset=["sale_id"], keep="first").copy()

    df["store_code"] = df["store_code"].apply(clean_text)
    df["branch"] = df["branch"].apply(clean_text)
    df["province"] = df["province"].apply(clean_text)
    df["region"] = df["region"].apply(lambda v: clean_text(v, default=pd.NA))
    df["product_name"] = df["product_name"].apply(clean_text)
    df["category"] = df["category"].apply(clean_text)
    df["sale_date"] = df["sale_date"].apply(parse_mixed_date)

    df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce").fillna(0).astype(int)
    df["unit_price"] = df["unit_price"].apply(clean_number)
    df["discount_percent"] = df["discount_percent"].apply(clean_number).fillna(0.0)

    df = df.dropna(subset=["sale_date", "unit_price"])
    df = df[(df["quantity"] > 0) & (df["unit_price"] >= 0)].copy()

    # region บางแถวไม่มีค่า -> เติมจาก store_code เดียวกันที่มีค่า region อยู่แล้ว, ถ้าไม่มีเลยค่อย fallback เป็น Unknown
    region_map = (df.dropna(subset=["region"])
                    .drop_duplicates("store_code")
                    .set_index("store_code")["region"])
    df["region"] = df["region"].fillna(df["store_code"].map(region_map)).fillna("Unknown")

    # dim_store: store_code ผูก 1:1 กับ branch/province/region หลัง normalize แล้ว
    dim_store = (df[["store_code", "branch", "province", "region"]]
                 .drop_duplicates("store_code")
                 .sort_values("store_code")
                 .reset_index(drop=True))
    dim_store.insert(0, "store_id", range(1, len(dim_store) + 1))

    # dim_product
    product_candidates = df[["product_name", "category"]].copy()
    product_candidates["_unknown_category"] = product_candidates["category"].eq("Unknown")
    dim_product = (product_candidates.sort_values(["product_name", "_unknown_category", "category"])
                   .drop_duplicates("product_name").drop(columns="_unknown_category")
                   .sort_values(["category", "product_name"]).reset_index(drop=True))
    dim_product.insert(0, "product_id", range(1, len(dim_product) + 1))

    # dim_date
    dim_date = (df[["sale_date"]].drop_duplicates().sort_values("sale_date")
                .reset_index(drop=True).rename(columns={"sale_date": "full_date"}))
    dim_date["date_id"] = dim_date["full_date"].dt.strftime("%Y%m%d").astype(int)
    dim_date["day"] = dim_date["full_date"].dt.day
    dim_date["month"] = dim_date["full_date"].dt.month
    dim_date["month_name"] = dim_date["full_date"].dt.month_name()
    dim_date["quarter"] = "Q" + dim_date["full_date"].dt.quarter.astype(str)
    dim_date["year"] = dim_date["full_date"].dt.year
    dim_date = dim_date[["date_id", "full_date", "day", "month", "month_name", "quarter", "year"]]

    print(f"[Phase 2A - Transform/Dimensions] stores={len(dim_store)}, products={len(dim_product)}, dates={len(dim_date)}")
    return df, dim_store, dim_product, dim_date


# Phase 2B: Transform - Fact Table

def transform_fact(df: pd.DataFrame, dim_store: pd.DataFrame, dim_product: pd.DataFrame, dim_date: pd.DataFrame) -> pd.DataFrame:
    mapped = df.merge(dim_store[["store_id", "store_code"]], on="store_code", how="left", validate="many_to_one")
    mapped = mapped.merge(dim_product[["product_id", "product_name"]], on="product_name", how="left", validate="many_to_one")
    mapped = mapped.merge(dim_date[["date_id", "full_date"]], left_on="sale_date", right_on="full_date", how="left", validate="many_to_one")

    mapped["total_amount"] = (mapped["quantity"] * mapped["unit_price"] * (1 - mapped["discount_percent"] / 100)).round(2)

    fact_sales = mapped[[
        "sale_id", "store_id", "product_id", "date_id",
        "quantity", "unit_price", "discount_percent", "total_amount",
    ]].rename(columns={"sale_id": "transaction_id"})

    fact_sales[["store_id", "product_id", "date_id"]] = fact_sales[["store_id", "product_id", "date_id"]].astype(int)
    fact_sales["discount_percent"] = fact_sales["discount_percent"].round(2)
    fact_sales["total_amount"] = fact_sales["total_amount"].round(2)

    print(f"[Phase 2B - Transform/Fact] facts={len(fact_sales)}")
    return fact_sales


# Phase 3A: Load - ตั้งค่า SQLite Warehouse

def setup_warehouse() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON;")
    print(f"[Phase 3A - Load/Setup] connected to warehouse -> {DB_PATH}")
    return conn


# Phase 3B: Load - บังคับใช้ Star Schema Relationship

def enforce_star_schema(conn: sqlite3.Connection) -> None:
    conn.executescript("""
    DROP TABLE IF EXISTS fact_sales;
    DROP TABLE IF EXISTS dim_store;
    DROP TABLE IF EXISTS dim_product;
    DROP TABLE IF EXISTS dim_date;

    CREATE TABLE dim_store (
        store_id INTEGER PRIMARY KEY,
        store_code TEXT NOT NULL UNIQUE,
        branch TEXT NOT NULL,
        province TEXT NOT NULL,
        region TEXT NOT NULL
    );

    CREATE TABLE dim_product (
        product_id INTEGER PRIMARY KEY,
        product_name TEXT NOT NULL,
        category TEXT NOT NULL,
        UNIQUE(product_name, category)
    );

    CREATE TABLE dim_date (
        date_id INTEGER PRIMARY KEY,
        full_date TEXT NOT NULL UNIQUE,
        day INTEGER NOT NULL,
        month INTEGER NOT NULL,
        month_name TEXT NOT NULL,
        quarter TEXT NOT NULL,
        year INTEGER NOT NULL
    );

    CREATE TABLE fact_sales (
        transaction_id TEXT PRIMARY KEY,
        store_id INTEGER NOT NULL REFERENCES dim_store(store_id),
        product_id INTEGER NOT NULL REFERENCES dim_product(product_id),
        date_id INTEGER NOT NULL REFERENCES dim_date(date_id),
        quantity INTEGER NOT NULL CHECK(quantity > 0),
        unit_price REAL NOT NULL CHECK(unit_price >= 0),
        discount_percent REAL NOT NULL CHECK(discount_percent >= 0 AND discount_percent <= 100),
        total_amount REAL NOT NULL CHECK(total_amount >= 0)
    );
    """
    )
    print("[Phase 3B - Load/Star Schema] dim_store, dim_product, dim_date, fact_sales created")


# Phase 3C: Load - ผลักข้อมูลลง Warehouse

def load_data(conn: sqlite3.Connection, dim_store: pd.DataFrame, dim_product: pd.DataFrame,
              dim_date: pd.DataFrame, fact_sales: pd.DataFrame) -> None:
    dim_store.to_sql("dim_store", conn, if_exists="append", index=False)
    dim_product.to_sql("dim_product", conn, if_exists="append", index=False)
    dim_date.to_sql("dim_date", conn, if_exists="append", index=False)
    fact_sales.to_sql("fact_sales", conn, if_exists="append", index=False)
    conn.commit()
    print(f"[Phase 3C - Load/Push] rows loaded -> "
          f"dim_store={len(dim_store)}, dim_product={len(dim_product)}, "
          f"dim_date={len(dim_date)}, fact_sales={len(fact_sales)}")


# Verification: ทดสอบคิวรีจาก Warehouse

def verify(conn: sqlite3.Connection) -> None:
    sql_by_province = """
    SELECT s.province, ROUND(SUM(f.total_amount), 2) AS total_sales
    FROM fact_sales f
    JOIN dim_store s ON f.store_id = s.store_id
    GROUP BY s.province
    ORDER BY total_sales DESC;
    """
    sql_top_products = """
    SELECT p.product_name, p.category, SUM(f.quantity) AS units_sold, ROUND(SUM(f.total_amount), 2) AS total_sales
    FROM fact_sales f
    JOIN dim_product p ON f.product_id = p.product_id
    GROUP BY p.product_id, p.product_name, p.category
    ORDER BY total_sales DESC
    LIMIT 5;
    """
    by_province = pd.read_sql_query(sql_by_province, conn)
    top_products = pd.read_sql_query(sql_top_products, conn)

    print("[Verify] ยอดขายแยกตามจังหวัด")
    print(by_province.to_string(index=False))
    print("\n[Verify] Top 5 สินค้าขายดี")
    print(top_products.to_string(index=False))


# Main

if __name__ == "__main__":
    raw = extract()
    clean_df, dim_store, dim_product, dim_date = transform_dimensions(raw)
    fact_sales = transform_fact(clean_df, dim_store, dim_product, dim_date)

    connection = setup_warehouse()
    try:
        enforce_star_schema(connection)
        load_data(connection, dim_store, dim_product, dim_date, fact_sales)
        verify(connection)
    finally:
        connection.close()

    print(f"\nETL Pipeline run successfully! -> {DB_PATH}")